### ISSUE TITLE
MDI missing icons

### ISSUE THREAD

**Issue by SwatkinsVU** [iconify/api.js#4]
I've set up this api and pointed my application to it. After doing so, it seems some of the icons from the MDI set that work when using the CDN api are no longer available. Examples are 'mdi:check-bold' and 'mdi:table-clock'. This persists even after specifying version 1.1.461 for @iconify/json in the optional dependencies.

**Comment by cyberalien** [comment]
Thanks for reporting!

Icons you've listed are available in 1.1.461, probably issue is browser cache.

I've updated code to support latest version of `@iconify/json` package and updated dependencies.

**Comment by SwatkinsVU** [comment]
Confirmed fixed! Didn't know about the localStorage cache before. Thanks for the help.
